interface Avatar {
  height: number;
  uri: string;
  url_list: string[];
  url_prefix: string | null;
  width: number;
}

interface UserListItem {
  accept_private_policy: boolean;
  account_labels: any | null;
  account_region: string;
  ad_cover_url: any | null;
  advance_feature_item_order: any | null;
  advanced_feature_info: any | null;
  apple_account: number;
  authority_status: number;
  avatar_168x168: Avatar;
  avatar_300x300: Avatar;
  avatar_larger: Avatar;
  avatar_medium: Avatar;
  avatar_thumb: Avatar;
  avatar_uri: string;
  aweme_count: number;
  bind_phone: string;
  bold_fields: any | null;
  can_message_follow_status_list: any | null;
  can_set_geofencing: any | null;
  cha_list: any | null;
  comment_filter_status: number;
  comment_setting: number;
  commerce_user_level: number;
  cover_url: any[];
  create_time: number;
  custom_verify: string;
  cv_level: string;
  download_prompt_ts: number;
  download_setting: number;
  duet_setting: number;
  enabled_filter_all_comments: boolean;
  enterprise_verify_reason: string;
  events: any | null;
  fake_data_info: any;
  favoriting_count: number;
  fb_expire_time: number;
  follower_count: number;
  following_count: number;
  geofencing: any | null;
  google_account: string;
  has_email: boolean;
  has_facebook_token: boolean;
  has_insights: boolean;
  has_orders: boolean;
  has_twitter_token: boolean;
  has_youtube_token: boolean;
  hide_search: boolean;
  homepage_bottom_toast: any | null;
  ins_id: string;
  is_ad_fake: boolean;
  is_block: boolean;
  is_discipline_member: boolean;
  is_mute: number;
  is_mute_lives: number;
  is_mute_non_story_post: number;
  is_mute_story: number;
  is_phone_binded: boolean;
  is_star: boolean;
  item_list: any | null;
  language: string;
  live_agreement: number;
  live_commerce: boolean;
  live_verify: number;
  mention_status: number;
  mutual_relation_avatars: any | null;
  need_points: any | null;
  need_recommend: number;
  nickname: string;
  original_musician: any;
  platform_sync_info: any | null;
  prevent_download: boolean;
  react_setting: number;
  region: string;
  relative_users: any | null;
  reply_with_video_flag: number;
  room_id: number;
  search_highlight: any | null;
  sec_uid: string;
  secret: number;
  share_info: any;
  share_qrcode_uri: string;
  shield_comment_notice: number;
  shield_digg_notice: number;
  shield_edit_field_info: any | null;
  shield_follow_notice: number;
  short_id: string;
  show_image_bubble: boolean;
  signature: string;
  special_account: any;
  special_lock: number;
  status: number;
  stitch_setting: number;
  total_favorited: number;
  tw_expire_time: number;
  twitter_id: string;
  twitter_name: string;
  type_label: any | null;
  uid: string;
  unique_id: string;
  unique_id_modify_time: number;
  user_canceled: boolean;
  user_mode: number;
  user_period: number;
  user_profile_guide: any | null;
  user_rate: number;
  user_spark_info: any;
  user_tags: any | null;
  verification_type: number;
  verify_info: string;
  video_icon: any;
  white_cover_url: any | null;
  with_commerce_entry: boolean;
  with_shop_entry: boolean;
  youtube_channel_id: string;
  youtube_channel_title: string;
  youtube_expire_time: number;
}

export interface UserFollowingResponse {
  has_more: boolean;
  max_time: number;
  total: number;
  followings: UserListItem[];
}